<?php

return [
    'en' => [
        1 => '<div class="error">Data Error</div>',
        2 => '<div class="error">Select plan</div>',
        3 => '<div class="error">Enter amount</div>',
        4 => '<div class="error">Select payment system</div>',
        5 => '<div class="error">Sum below minimum</div>',
        6 => '<div class="error">Sum above maximum</div>',
		7 => '<div class="error">Sum equivalent to less than minimum for plan</div>',
		8 => '<div class="error">You have the maximum allowed number of deposits for this payment system</div>',
		9 => '<div class="error">Your amount exceeds the current limit</div>',
		10 => '<div class="success">Operation done</div>',
		17 => '<div class="success">Application has been sent for consideration</div>',
		11 => '<div class="error">Your account is not enough</div>',
        20 => '<div class="success">Operation canceled</div>',
		21 => '<div class="error">You can invest only in the investment period</div>',
		22 => '<div class="error">WMTransId cannot be less than 10 characters</div>',
    ],
	'ru' => [
        1 => '<div class="error">Ошибка данных</div>',
        2 => '<div class="error">Выберите план</div>',
        3 => '<div class="error">Введите сумму</div>',
        4 => '<div class="error">Выберите платежную систему</div>',
        5 => '<div class="error">Сумма меньше минимальной</div>',
        6 => '<div class="error">Сумма больше максимальной</div>',
		7 => '<div class="error">Сумма в долларах меньше минимально возможной к инвестированию</div>',
		8 => '<div class="error">Общая сумма инвестиций по этой платежной системе превышает текущий лимит</div>',
		9 => '<div class="error">Вы указали сумму больше, чем позволяет текущий лимит</div>',
		10 => '<div class="success">Операция выполнена</div>',
		17 => '<div class="success">Заявка отправлена на рассмотрение</div>',
		11 => '<div class="error">На вашем счету недостаточно</div>',
        20 => '<div class="success">Операция отменена</div>',
		21 => '<div class="error">Инвестировать можно лишь в инвестиционный период</div>',
		22 => '<div class="error">WMTransId не может быть меньше 10 символов</div>',
    ],
];
