<?php

return [
    'en' => [
		1 => '<div class="error">Data error</div>',
        2 => '<div class="error">Enter login</div>',
        3 => '<div class="error">Enter email</div>',
        4 => '<div class="error">Enter password</div>',
        5 => '<div class="error">Repeat password</div>',
        7 => '<div class="error">Invalid Login Format</div>',
        8 => '<div class="error">Invalid Email Format</div>',
        9 => '<div class="error">Wrong password Format</div>',
        10 => '<div class="error">Wrong password Format</div>',
        12 => '<div class="error">User with this login already exists</div>',
        13 => '<div class="error">User with this email already exists</div>',
        14 => '<div class="error">Passwords do not match</div>',
        15 => '<div class="error">Registration already completed from this IP</div>',
        16 => '<div class="error">Confirm rules</div>',
        17 => '<div class="error">Confirm the rules</div>',
		18 => '<div class="error">Password cannot be less than 4 characters</div>',
		19 => '<div class="error">Login cannot be less than 5 characters</div>',
        20 => '<div class="success">You have successfully registered</div>',
    ],
	'ru' => [
		1 => '<div class="error">Ошибка данных</div>',
        2 => '<div class="error">Введите login</div>',
        3 => '<div class="error">Введите email</div>',
        4 => '<div class="error">Введите пароль</div>',
        5 => '<div class="error">Повторить пароль</div>',
        7 => '<div class="error">Недопустимый формат Логина</div>',
        8 => '<div class="error">Недопустимый формат емейла</div>',
        9 => '<div class="error">Неправильный формат пароля</div>',
        10 => '<div class="error">Неправильный формат пароля</div>',
        12 => '<div class="error">Пользователь с таким логином уже существует</div>',
        13 => '<div class="error">Пользователь с таким email уже существует</div>',
        14 => '<div class="error">Пароли не совпадают </div>',
        15 => '<div class="error">Регистрация уже завершена с этого IP</div>',
        16 => '<div class="error">Подтвердите правила</div>',
        17 => '<div class="error">Подтвердите правила</div>',
		18 => '<div class="error">Пароль не может быть меньше 4 символов</div>',
		19 => '<div class="error">Логин не может быть меньше 5 символов</div>',
        20 => '<div class="success">Вы успешно зарегистрировались</div>',
    ],
];
