<?php

return [
    'en' => [
        1 => '<div class="error">Data Error</div>',
        2 => '<div class="error">Enter login</div>',
        3 => '<div class="error">Enter password</div>',
        5 => '<div class="error">Invalid login format or email</div>',
        6 => '<div class="error">Wrong password format</div>',
        8 => '<div class="error">User with login <br>email not found</div>',
        9 => '<div class="error">Wrong password</div>',
        10 => '<div class="error">Your account has been suspended (reason: multy accounts)</div>',
		16 => '<div class="error">Confirm rules</div>',
		17 => '<div class="error">Confirm that you are not a robot</div>',
		23 => '<div class="error">Enter email</div>',
		25 => '<div class="error">Repeat password</div>',
		32 => '<div class="error">User with this login already exists</div>',
        33 => '<div class="error">User with this email already exists</div>',
		34 => '<div class="error">Passwords do not match</div>',
		35 => '<div class="error">Registration already completed from this IP</div>',
		38 => '<div class="error">Password cannot be less than 4 characters</div>',
		39 => '<div class="error">Login cannot be less than 5 characters</div>',
        30 => '<div class="success">You have successfully registered</div>',
        47 => '<div class="error">Invalid Login Format</div>',
        48 => '<div class="error">Invalid Email Format</div>',
		49 => '<div class="error">Wrong password Format</div>',
		55 => '<div class="error">You have already submitted applications within 24 hours</div>',
		50 => '<div class="success">Reset Data sent to your email</div>',
    ],
	'ru' => [
        1 => '<div class="error">Ошибка данных</div>',
        2 => '<div class="error">Введите логин</div>',
        3 => '<div class="error">Ведите пароль</div>',
        5 => '<div class="error">Недействительный формат входа или адрес электронной почты</div>',
        6 => '<div class="error">Пароль имеет неверный формат</div>',
        8 => '<div class="error">Пользователь с таким логином <br> электронной почтой не найден</div>',
        9 => '<div class="error">Пароль неверный </div>',
        10 => '<div class="error">Ваш аккаунт был заблокирован (причина: мультиаккаунт)</div>',
		16 => '<div class="error">Подтвердите правила</div>',
		17 => '<div class="error">Подтвердите, что вы не робот</div>',
        23 => '<div class="error">Введите email</div>',
        25 => '<div class="error">Повторите пароль</div>',
        32 => '<div class="error">Пользователь с таким логином уже существует</div>',
        33 => '<div class="error">Пользователь с таким email уже существует</div>',
		34 => '<div class="error">Пароли не совпадают </div>',
		35 => '<div class="error">Регистрация уже завершена с этого IP</div>',
		38 => '<div class="error">Пароль не может быть меньше 4 символов</div>',
		39 => '<div class="error">Логин не может быть меньше 5 символов</div>',
        30 => '<div class="success">Вы успешно зарегистрировались</div>',
        47 => '<div class="error">Недопустимый формат Логина</div>',
        48 => '<div class="error">Недопустимый формат емейла</div>',
        49 => '<div class="error">Неправильный формат пароля</div>',
		55 => '<div class="error">Вы уже отправляли заявку за последние 24 часа</div>',
		50 => '<div class="success">Данные для сброса отправленны на ваш email</div>',
    ],

];